version: '3'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # only for test/develoment
    container_name: redis-translate
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
